//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using com.shephertz.app42.paas.sdk.csharp;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using com.shephertz.app42.paas.sdk.csharp.gift;
namespace AssemblyCSharp
{
	public class GiftCallBack : App42CallBack
	{
		public static string  giftName = "";
		public static int  giftCount=0;

		public void OnSuccess (object obj)
		{
			if (obj is Gift) {
								Gift giftObj = (Gift)obj;
								//	result = gameObj.ToString ();
								Debug.Log ("Gift Response : " + giftObj.ToString ());
				giftName=giftObj.GetName();
						}
			if (obj is App42Response) {
				App42Response resposne = (App42Response)obj;
				//	result = gameObj.ToString ();
				Debug.Log ("Gift Response : " + resposne.GetTotalRecords ());
				giftCount=resposne.GetTotalRecords ();
				

			}
			LeaderBoard.yourGift = true;
		}
		
		public void OnException (Exception e)
		{
			//	result = e.ToString ();
			Debug.Log ("EXCEPTION : " + e);
			
		}
		
	}
	
}




